config/routes.rb
Rails.application.routes.draw do
  get 'calendar_week/show'

  get 'calendar/show'

  root :to => 'pages#home'
  resources :user_sessions
  resources :users
  resources :businesses, shallow: true do
    resources :user_businesses
  end
  resources :clients
  resources :scheduled_locations
  resource :calendar, only: [:show], controller: :calendar
  resource :mow_flow, only: [:show], controller: :mow_flow
  resources :calendar_week do
    collection do
      patch :sort
    end
  end

  get 'home', to: 'pages#home', as: 'home'
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'my_business', to: 'businesses#show', as: 'my_business'
  get 'client_jobs/:id', to: 'scheduled_locations#client_jobs', as: 'client_jobs'
  get 'reschedule_job/:id', to: 'scheduled_locations#reschedule_job', as: 'reschedule_job'
  patch 'reschedule_job/:id', to: 'scheduled_locations#reschedule_job_update', as: 'reschedule_job_update'
  get 'non_optimized', to: 'mow_flow#show_one_day', as: 'non_optimized'
  post 'mow_flow_opto', to: 'mow_flow#optimize_list', as: 'mow_flow_opto'
  get 'mow_flow_save', to: 'mow_flow#save_list', as: 'mow_flow_save'
  get 'in_progress', to: 'mow_flow#in_progress', as: 'in_progress'
  get 'print_list', to: 'mow_flow#print_list', as: 'print_list'
  post 'save_progress', to: 'mow_flow#save_progress', as: 'save_progress'
  get 'reschedule_in_progress', to: 'mow_flow#reschedule_in_progress', as: 'reschedule_in_progress'
  post 'save_reschedule_in_progress', to: 'mow_flow#save_reschedule_in_progress', as: 'save_reschedule_in_progress'
  get 'skipped_jobs', to: 'mow_flow#skipped_jobs', as: 'skipped_jobs'
  post 'save_skipped_jobs', to: 'mow_flow#save_skipped_jobs', as: 'save_skipped_jobs'
  get 'reschedule_skipped_jobs', to: 'mow_flow#reschedule_skipped_jobs', as: 'reschedule_skipped_jobs'
  post 'save_reschedule_skipped_jobs', to: 'mow_flow#save_reschedule_skipped_jobs', as: 'save_reschedule_skipped_jobs'
  get 'cancel_skipped_jobs', to: 'mow_flow#cancel_skipped_jobs', as: 'cancel_skipped_jobs'
  post 'save_cancel_skipped_jobs', to: 'mow_flow#save_cancel_skipped_jobs', as: 'save_cancel_skipped_jobs'
  get 'new_depot', to: 'scheduled_locations#new_depot', as: 'new_depot'
  post 'create_depot', to: 'scheduled_locations#create_depot', as: 'create_depot'
  get 'edit_depot', to: 'scheduled_locations#edit_depot', as: 'edit_depot'
  patch 'update_depot', to: 'scheduled_locations#update_depot', as: 'update_depot'
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/scheduled_location.rb
class ScheduledLocation < ApplicationRecord
  belongs_to :client, :foreign_key => 'client_id'
  belongs_to :business, :foreign_key => 'business_id'
  belongs_to :duration, :foreign_key => 'duration_id'
  belongs_to :extra_duration, :foreign_key => 'extra_duration_id'
end

app/controllers/scheduled_locations_controller.rb
class ScheduledLocationsController < ApplicationController
  include HTTParty
  def index
    @scheduled_locations = if params[:location_desc]
      ScheduledLocation.where('location_desc LIKE ? AND depot IS ?', "%#{params[:location_desc]}%", nil)
    else
      ScheduledLocation.where("depot IS ?", nil)
    end
    @clear_search = if params[:location_desc]
      true
    else
      false
    end
  end

  def new_depot
    @scheduled_location = ScheduledLocation.new
    @business = get_business
    render 'new_depot'
  end

  def create_depot
    @business = get_business
    @scheduled_location = ScheduledLocation.new(scheduled_location_params)
    # build string for api call
    location = build_location_string(@scheduled_location)
    # get places ID and coordinates
    response_hash = get_place_id_and_coordinates(location)
    longitude = response_hash['geometry']['location']['lng']
    latitude = response_hash['geometry']['location']['lat']
    @scheduled_location.coordinates = "#{longitude},#{latitude}"
    @scheduled_location.google_place_id = response_hash['place_id']
    
    @scheduled_location.business_id = @business.id
    # get or create client id
    @client = get_client
    @scheduled_location.client_id = @client.id
    @scheduled_location.duration_id = 1
    @scheduled_location.extra_duration_id = 6
    @scheduled_location.depot = true

    respond_to do |format|
      if @scheduled_location.save
        format.html { redirect_to my_business_path, notice: 'Business Depot was successfully created.' }
      else
        format.html { render new_depot }
        format.json { render json: @scheduled_location.errors, status: :unprocessable_entity }
      end
    end

  end

  def edit_depot
    @user_business = UserBusiness.where('user_id = ?', current_user).first
    @business = Business.where('id = ?', @user_business.business_id).first
    @scheduled_location = ScheduledLocation.where('business_id = ? AND depot = ?', @business.id, true).first
  end

  def update_depot
    @user_business = UserBusiness.where('user_id = ?', current_user).first
    @business = Business.where('id = ?', @user_business.business_id).first
    @scheduled_location = ScheduledLocation.where('business_id = ? AND depot = ?', @business.id, true).first
    #copy params for update
    updated_scheduled_location_params = scheduled_location_params
    # create old Location string to check for changes on update
    @old_location = build_location_string(@scheduled_location)
    #create new location string
    @updated_location = scheduled_location_params
    @new_location = build_location_string_from_hash(@updated_location)
    puts "old loc: #{@old_location}, new loc: #{@new_location}"
    #update google place ID and coordinates if new location entered
    unless @old_location == @new_location
      # get places ID and coordinates
      response_hash = get_place_id_and_coordinates(@new_location)
      longitude = response_hash['geometry']['location']['lng']
      latitude = response_hash['geometry']['location']['lat']
      puts "sched loc geo: #{response_hash['geometry']}"
      puts "sched loc place id: #{response_hash['place_id']}"
      updated_scheduled_location_params[:coordinates] = "#{longitude},#{latitude}"
      updated_scheduled_location_params[:google_place_id] = response_hash['place_id']
    end
    respond_to do |format|
      if @scheduled_location.update(updated_scheduled_location_params)
        format.html { redirect_to my_business_path, notice: 'Job was successfully rescheduled.' }
      else
        format.html { render :edit }
        format.json { render json: @scheduled_location.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @scheduled_location = ScheduledLocation.new
    @clients = Client.all
    @durations = Duration.all
    @extra_duration_zero = ExtraDuration.where('id = ?', 6).first
    @business = get_business
  end

  def create
    @business = get_business
    @extra_duration_zero = ExtraDuration.where('id = ?', 6).first
    @scheduled_location = ScheduledLocation.new(scheduled_location_params)
    # build string for api call
    location = build_location_string(@scheduled_location)
    # get places ID and coordinates
    response_hash = get_place_id_and_coordinates(location)
    longitude = response_hash['geometry']['location']['lng']
    latitude = response_hash['geometry']['location']['lat']
    @scheduled_location.coordinates = "#{longitude},#{latitude}"
    @scheduled_location.google_place_id = response_hash['place_id']

    @scheduled_location.business_id = @business.id
    @scheduled_location.extra_duration_id = @extra_duration_zero.id
    # Change Mow Frequency input to integer and get next mow date
    mow_freq = get_mow_freq_as_int(@scheduled_location.mow_frequency)
    @scheduled_location.next_mow_date = get_next_mow_date(@scheduled_location.date_mowed, mow_freq)
    @scheduled_location.mow_frequency = mow_freq
    
    respond_to do |format|
      if @scheduled_location.save
        format.html { redirect_to scheduled_locations_path, notice: 'Job was successfully created.' }
        # format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @scheduled_location.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @scheduled_location = ScheduledLocation.find(params[:id])
    @duration_obj = Duration.where('id = ?', @scheduled_location.duration_id).first
    @duration = @duration_obj.duration_desc
  end

  def edit
    @scheduled_location = ScheduledLocation.find(params[:id])
    @clients = Client.all
    @durations = Duration.all
    @extra_duration = ExtraDuration.where('id = ?', @scheduled_location.extra_duration_id).first
    @business = get_business
  end
  
  def update
    @scheduled_location = ScheduledLocation.find(params[:id])
    #copy params for update
    updated_scheduled_location_params = scheduled_location_params
    # create old Location string to check for changes on update
    @old_location = build_location_string(@scheduled_location)
    #create new location string
    @updated_location = scheduled_location_params
    @new_location = build_location_string_from_hash(@updated_location)

    #update google place ID and coordinates if new location entered
    unless @old_location == @new_location
      # get places ID and coordinates
      response_hash = get_place_id_and_coordinates(@new_location)
      longitude = response_hash['geometry']['location']['lng']
      latitude = response_hash['geometry']['location']['lat']
      updated_scheduled_location_params[:coordinates] = "#{longitude},#{latitude}"
      updated_scheduled_location_params[:google_place_id] = response_hash['place_id']
    end

    @extra_duration = ExtraDuration.where('id = ?', @scheduled_location.extra_duration_id).first
    @scheduled_location.extra_duration_id = @extra_duration.id
    # Change Mow Frequency input to integer and get next mow date
    
    mow_freq = get_mow_freq_as_int(scheduled_location_params["mow_frequency"])
    updated_scheduled_location_params["next_mow_date"] = get_next_mow_date(scheduled_location_params["date_mowed"], mow_freq)
    updated_scheduled_location_params["mow_frequency"] = mow_freq

    respond_to do |format|
      if @scheduled_location.update(updated_scheduled_location_params)
        format.html { redirect_to @scheduled_location, notice: 'Job was successfully updated.' }
        # format.json { render :show, status: :created, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @scheduled_location.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @scheduled_location = ScheduledLocation.find(params[:id])
    @scheduled_location.destroy
    respond_to do |format|
      format.html { redirect_to scheduled_locations_path, notice: 'Job was successfully deleted.' }
    end
  end

  def reschedule_job
    @scheduled_location = ScheduledLocation.find(params[:id])
    render 'reschedule_job'
  end
  
  def reschedule_job_update
    @scheduled_location = ScheduledLocation.find(params[:id])
    respond_to do |format|
      if @scheduled_location.update(scheduled_location_params)
        format.html { redirect_to @scheduled_location, notice: 'Job was successfully rescheduled.' }
        # format.json { render :show, status: :created, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @scheduled_location.errors, status: :unprocessable_entity }
      end
    end
  end

  def client_jobs
    @client = Client.find(params[:id])
    @scheduled_locations = ScheduledLocation.where("client_id = ?", @client.id)
    render 'client_jobs'
  end


  private
  
    # Use callbacks to share common setup or constraints between actions.
    def get_google_places_api_key
      # get google places api key from database
      key_hash = Key.where('id = ?', 1).first
      key = key_hash.key
      return key
    end

    def get_business
      @user_business = UserBusiness.where('user_id = ?', current_user).first
      @business = Business.where('id = ?', @user_business.business_id).first
    end

    def get_client
      @user_business = UserBusiness.where('user_id = ?', current_user).first
      @business = Business.where('id = ?', @user_business.business_id).first
      @client = Client.find_or_create_by(business_id: @business.id)
    end

    # Change Mow Frequency input to integer
    def get_mow_freq_as_int(mow_freq)
      mow_frequency_as_string = mow_freq
      return mow_frequency_as_string.to_i
    end

    # Create Next Mow Date
    def get_next_mow_date(date_last_mowed, mow_freq)  
      date_mowed = @scheduled_location.date_mowed
      return date_mowed.days_since(mow_freq)
    end

    def build_location_string(sched_loc)
      location = "#{sched_loc.street_address}, #{sched_loc.city}, #{sched_loc.state}"

app/helpers/scheduled_locations_helper.rb
module ScheduledLocationsHelper
end

app/views/scheduled_locations/_form.html.erb
<%= form_with(model: scheduled_location, local: true) do |f| %>
  <% if scheduled_location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scheduled_location.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% scheduled_location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Client Name" %><br>
    <%= f.collection_select(:client_id, Client.all, :id, :full_name) %>
  </div>

  <div class="field">
    <%= f.label "Location Description" %>
    <%= f.text_field :location_desc, id: :location_desc %>
  </div>
  
  <div class="field">
    <%= f.label :street_address %>
    <%= f.text_field :street_address, id: :street_address %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city, id: :city %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state, id: :state %>
  </div>

  <div class="field">
    <%= f.label :zip %>
    <%= f.text_field :zip, id: :zip %>
  </div>

  <div class="field">
    <%= f.label :start_season %>
    <%= f.date_select :start_season, {order: [:month, :day, :year], prompt: { day: 'Select day', month: 'Select month', year: 'Select year' }, start_year: Date.today.year, end_year: Date.today.year + 1}, {required: true} %>
  </div>

  <div class="field">
    <%= f.label :end_season %>
    <%= f.date_select :end_season, {order: [:month, :day, :year], prompt: { day: 'Select day', month: 'Select month', year: 'Select year' }, start_year: Date.today.year, end_year: Date.today.year + 1}, {required: true} %>
  </div>

  <div class="field">
    <%= f.label :date_mowed %>
    <%= f.date_select :date_mowed, {order: [:month, :day, :year], prompt: { day: 'Select day', month: 'Select month', year: 'Select year' }, start_year: Date.today.year, end_year: Date.today.year + 1}, {required: true} %>
  </div>

  <div class="field">
    <%= f.label "Mow Frequency (Number of days between mows)" %>
    <%= f.text_field :mow_frequency, id: :mow_frequency %>
  </div>

   <div class="field">
    <%= f.label "Day Of the Week (Optional)" %>
    <%= f.text_field :day_of_week, id: :day_of_week %>
  </div>

  <div class="field">
    <%= f.label "Average Duration" %><br>
    <%= f.collection_select(:duration_id, Duration.all, :duration, :duration_desc) %>
  </div>

  <div class="field">
    <%= f.label "User Notes (Optional)" %>
    <%= f.text_field :user_notes, id: :user_notes %>
  </div>
  

  <div class="actions">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/scheduled_locations/client_jobs.html.erb
<div class="row">
  <%= render :partial => 'partials/dashboard' %>

  <div class="col-xs-8 offset-md-1">
    <h1><%= "#{@client.full_name}'s Jobs" %> </h1>

    <table>
      <tr>
        <th>Client ID</th>
        <th>Location Description</th>
        <th>Street Address</th>
        <th>City</th>
        <th>Date Last Mowed</th>
        <th>Next Mow Date</th>
      </tr>

      <% @scheduled_locations.each do |job| %>
        <tr>
          <td><%= job.client_id %></td>
          <td><%= job.location_desc %></td>
          <td><%= job.street_address %></td>
          <td><%= job.city %></td>
          <td><%= job.date_mowed %></td>
          <td><%= job.next_mow_date %></td>
          <td><%= link_to 'Details', scheduled_location_path(job), :class => 'btn btn-primary' %></td>
        </tr>
      <% end %>
    </table>

    <%= link_to 'Back To Client', client_path(@client), :class => 'btn btn-primary' %>
  </div>
</div>

app/views/scheduled_locations/edit.html.erb
<div class="row">
  <%= render :partial => 'partials/dashboard' %>

  <div class="col-xs-8 offset-md-1">
    <h1>Edit Job</h1>

    <%= render 'form', scheduled_location: @scheduled_location %>

    <%= link_to 'View Job List', scheduled_locations_path, :class => 'btn btn-primary' %>
  </div>
</div>

app/views/scheduled_locations/edit_depot.html.erb
<div class="row">
  <%= render :partial => 'partials/dashboard' %>

  <div class="col-xs-8 offset-md-1">
    <h1>Edit Business Location</h1>

    <%= form_with(model: @scheduled_location, local: true, url: update_depot_path) do |f| %>
      <% if @scheduled_location.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@scheduled_location.errors.count, "error") %> prohibited this business location from being updated:</h2>
          <ul>
            <% @scheduled_location.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      
      <div class="field">
        <%= f.label "Business Depot Name" %>
        <%= f.text_field :location_desc, id: :location_desc %>
      </div>
      
      <div class="field">
        <%= f.label :street_address %>
        <%= f.text_field :street_address, id: :street_address %>
      </div>

      <div class="field">
        <%= f.label :city %>
        <%= f.text_field :city, id: :city %>
      </div>

      <div class="field">
        <%= f.label :state %>
        <%= f.text_field :state, id: :state %>
      </div>

      <div class="field">
        <%= f.label :zip %>
        <%= f.text_field :zip, id: :zip %>
      </div>

      <div class="actions">
        <%= f.submit "Update Business Location", :class => 'btn btn-primary'%>
      </div>
    <% end %>

  </div>
</div>

app/views/scheduled_locations/index.html.erb
<div class="row">
  <%= render :partial => 'partials/dashboard' %>

  <div class="col-xs-8 offset-md-1">
    <div class="row">
      <div class="col-6">
        <h1>Job List</h1>
      </div>
      <div class="col-6 my-auto">
      <%= form_tag(scheduled_locations_path, method: :get) do %>
        <div class="input-group">
          <%= text_field_tag :location_desc, params[:location_desc], :class => 'form-control' %>
          <div class="input-group-append">
            <%= submit_tag 'Search', name: nil, :class => 'btn btn-outline-primary' %>
          </div>
      </div>
      <% end %>
      </div>
    </div>

    <table class="table table-striped table-sm">
      <tr>
        <th>Client ID</th>
        <th>Location Description</th>
        <th>Street Address</th>
        <th>City</th>
        <th>Date Last Mowed</th>
        <th>Next Mow Date</th>
        <th></th>
        <th></th>

      </tr>

      <% @scheduled_locations.each do |job| %>
        <tr>
          <td><%= job.client_id %></td>
          <td><%= job.location_desc %></td>
          <td><%= job.street_address %></td>
          <td><%= job.city %></td>
          <td><%= job.date_mowed %></td>
          <td><%= job.next_mow_date %></td>
          <td><%= link_to 'Details', scheduled_location_path(job), :class => 'btn btn-primary btn-sm' %></td>
          <td><%= link_to 'Delete', scheduled_location_path(job), method: :delete, data: {confirm: 'Are you sure?'}, :class => 'btn btn-danger btn-sm' %></td>
        </tr>
      <% end %>
    </table>
    <% if @clear_search %>
      <%= link_to 'Clear Search', scheduled_locations_path, :class => 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/scheduled_locations/new.html.erb
<div class="row">
  <%= render :partial => 'partials/dashboard' %>

  <div class="col-xs-8 offset-md-1">
    <h1>Add Job</h1>
    <%= render 'form', scheduled_location: @scheduled_location %>
    <%= link_to 'Back', dashboard_path, :class => 'btn btn-primary' %>
  </div>
</div>

app/views/scheduled_locations/new_depot.html.erb
<div class="row">
  <%= render :partial => 'partials/dashboard' %>

  <div class="col-xs-8 offset-md-1">
    <h1>Enter Business Location</h1>

    <%= form_with(model: @scheduled_location, local: true, url: create_depot_path) do |f| %>
      <% if @scheduled_location.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@scheduled_location.errors.count, "error") %> prohibited this business location from being saved:</h2>
          <ul>
            <% @scheduled_location.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      
      <div class="field">
        <%= f.label "Business Depot Name" %>
        <%= f.text_field :location_desc, id: :location_desc %>
      </div>
      
      <div class="field">
        <%= f.label :street_address %>
        <%= f.text_field :street_address, id: :street_address %>
      </div>

      <div class="field">
        <%= f.label :city %>
        <%= f.text_field :city, id: :city %>
      </div>

      <div class="field">
        <%= f.label :state %>
        <%= f.text_field :state, id: :state %>
      </div>

      <div class="field">
        <%= f.label :zip %>
        <%= f.text_field :zip, id: :zip %>
      </div>

      <div class="actions">
        <%= f.submit "Save Location", :class => 'btn btn-primary' %>
      </div>
    <% end %>

  </div>
</div>

app/views/scheduled_locations/reschedule_job.html.erb
<div class="row">
  <%= render :partial => 'partials/dashboard' %>

  <div class="col-xs-8 offset-md-1">
    <h1>Reschedule Job</h1>
    <p>
      <strong>Client ID:</strong>
      <%= @scheduled_location.client_id %>
    </p>
    <p>
      <strong>Location Description:</strong>
      <%= @scheduled_location.location_desc %>
    </p>
    <%= form_with(model: @scheduled_location, local: true, url: reschedule_job_update_path) do |f| %>
      <% if @scheduled_location.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@scheduled_location.errors.count, "error") %> prohibited this job from being saved:</h2>

          <ul>
            <% @scheduled_location.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :next_mow_date %>
        <%= f.date_select :next_mow_date, {order: [:month, :day, :year], prompt: { day: 'Select day', month: 'Select month', year: 'Select year' }, start_year: Date.today.year, end_year: Date.today.year + 1}, {required: true} %>
      </div>

      <div class="field">
        <%= f.label "User Notes (Optional)" %>
        <%= f.text_field :user_notes, id: :user_notes %>
      </div>
      
      <div class="actions ">
        <%= f.submit :class => 'btn btn-primary' %>
      </div>
    <% end %>

    <%= link_to 'Back', dashboard_path, :class => 'btn btn-primary' %>
  </div>
</div>

app/views/scheduled_locations/show.html.erb
<div class="row">
  <%= render :partial => 'partials/dashboard' %>

  <div class="col-xs-4 offset-md-1">
    <p>
      <strong>Client ID:</strong>
      <%= @scheduled_location.client_id %>
    </p>
    <p>
      <strong>Location Description:</strong>
      <%= @scheduled_location.location_desc %>
    </p>
    <p>
      <strong>Street Address:</strong>
      <%= @scheduled_location.street_address %>
    </p>
    <p>
      <strong>City:</strong>
      <%= @scheduled_location.city %>
    </p>
    <p>
      <strong>State:</strong>
      <%= @scheduled_location.state %>
    </p>
    <p>
      <strong>Zip:</strong>
      <%= @scheduled_location.zip %>
    </p>
    <p>
      <strong>Start Season:</strong>
      <%= @scheduled_location.start_season %>
    </p>
    <p>
      <strong>End Season:</strong>
      <%= @scheduled_location.end_season %>
    </p>
    <p>
      <strong>Date Last Mowed:</strong>
      <%= @scheduled_location.date_mowed %>
    </p>
    <p>
      <strong>Next Mow Date:</strong>
      <%= @scheduled_location.next_mow_date %>
    </p>
    <p>
      <strong>Mowing Frequency:</strong>
      <%= @scheduled_location.mow_frequency %>
    </p>
    <p>
      <strong>Day of the week (If Specified):</strong>
      <%= @scheduled_location.day_of_week %>
    </p>
    <p>
      <strong>Average Duration:</strong>
      <%= @duration %>
    </p>
    <p>
      <strong>User Notes:</strong>
      <%= @scheduled_location.user_notes %>
    </p>

    <%= link_to 'Edit', edit_scheduled_location_path(@scheduled_location), :class => 'btn btn-primary' %>
    <%= link_to 'Delete', scheduled_location_path(@scheduled_location), method: :delete, data: {confirm: 'Are you sure?'}, :class => 'btn btn-primary' %>
    <%= link_to 'Reschedule Job', reschedule_job_path(@scheduled_location), :class => 'btn btn-primary' %>
    <%= link_to 'View Job List', scheduled_locations_path, :class => 'btn btn-primary' %>
  </div>
</div>