config/routes.rb
Rails.application.routes.draw do
  get 'calendar_week/show'

  get 'calendar/show'

  root :to => 'pages#home'
  resources :user_sessions
  resources :users
  resources :businesses, shallow: true do
    resources :user_businesses
  end
  resources :clients
  resources :scheduled_locations
  resource :calendar, only: [:show], controller: :calendar
  resource :mow_flow, only: [:show], controller: :mow_flow
  resources :calendar_week do
    collection do
      patch :sort
    end
  end

  get 'home', to: 'pages#home', as: 'home'
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'my_business', to: 'businesses#show', as: 'my_business'
  get 'client_jobs/:id', to: 'scheduled_locations#client_jobs', as: 'client_jobs'
  get 'reschedule_job/:id', to: 'scheduled_locations#reschedule_job', as: 'reschedule_job'
  patch 'reschedule_job/:id', to: 'scheduled_locations#reschedule_job_update', as: 'reschedule_job_update'
  get 'non_optimized', to: 'mow_flow#show_one_day', as: 'non_optimized'
  post 'mow_flow_opto', to: 'mow_flow#optimize_list', as: 'mow_flow_opto'
  get 'mow_flow_save', to: 'mow_flow#save_list', as: 'mow_flow_save'
  get 'in_progress', to: 'mow_flow#in_progress', as: 'in_progress'
  get 'print_list', to: 'mow_flow#print_list', as: 'print_list'
  post 'save_progress', to: 'mow_flow#save_progress', as: 'save_progress'
  get 'reschedule_in_progress', to: 'mow_flow#reschedule_in_progress', as: 'reschedule_in_progress'
  post 'save_reschedule_in_progress', to: 'mow_flow#save_reschedule_in_progress', as: 'save_reschedule_in_progress'
  get 'skipped_jobs', to: 'mow_flow#skipped_jobs', as: 'skipped_jobs'
  post 'save_skipped_jobs', to: 'mow_flow#save_skipped_jobs', as: 'save_skipped_jobs'
  get 'reschedule_skipped_jobs', to: 'mow_flow#reschedule_skipped_jobs', as: 'reschedule_skipped_jobs'
  post 'save_reschedule_skipped_jobs', to: 'mow_flow#save_reschedule_skipped_jobs', as: 'save_reschedule_skipped_jobs'
  get 'cancel_skipped_jobs', to: 'mow_flow#cancel_skipped_jobs', as: 'cancel_skipped_jobs'
  post 'save_cancel_skipped_jobs', to: 'mow_flow#save_cancel_skipped_jobs', as: 'save_cancel_skipped_jobs'
  get 'new_depot', to: 'scheduled_locations#new_depot', as: 'new_depot'
  post 'create_depot', to: 'scheduled_locations#create_depot', as: 'create_depot'
  get 'edit_depot', to: 'scheduled_locations#edit_depot', as: 'edit_depot'
  patch 'update_depot', to: 'scheduled_locations#update_depot', as: 'update_depot'
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_dashboard.html.erb
<div class="col-xs-2">
  <div class="nav flex-column">
    <div class="list-group" id="myList" role="tablist">
      <h3 class="list-group-item list-group-item">Dashboard</h3>
      <div id="accordion" role="tablist">
        <div class="card">
          <div class="card-header" role="tab" id="headingOne">
            <a class="list-group-item list-group-item-action dash-menu" role="tab" data-toggle="collapse" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">Clients</a>
          </div>
          <div id="collapseOne" class="collapse" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion">
            <div class="card-body">
              <div class="list-group" id="clientList" role="tablist">
                <%= link_to 'Client List', clients_path, :class => 'list-group-item list-group-item-action dash-action' %>
                <%= link_to 'Add Client', new_client_path, :class => 'list-group-item list-group-item-action dash-action' %>
              </div>
            </div>
          </div>
        </div>

        <div class="card">
          <div class="card-header" role="tab" id="headingTwo">
            <a class="list-group-item list-group-item-action dash-menu" role="tab" data-toggle="collapse" href="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">Jobs</a>
          </div>
          <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo" data-parent="#accordion">
            <div class="card-body">
              <div class="list-group" id="jobList" role="tablist">
                <%= link_to 'Job List', scheduled_locations_path, :class => 'list-group-item list-group-item-action dash-action' %>
                <%= link_to 'Add Job', new_scheduled_location_path, :class => 'list-group-item list-group-item-action dash-action' %>
              </div>
            </div>
          </div>
        </div>

        <div class="card">
          <div class="card-header" role="tab" id="headingThree">
            <a class="list-group-item list-group-item-action dash-menu" role="tab" data-toggle="collapse" href="#collapseThree" aria-expanded="true" aria-controls="collapseThree">Calendar</a>
          </div>
          <div id="collapseThree" class="collapse" role="tabpanel" aria-labelledby="headingThree" data-parent="#accordion">
            <div class="card-body">
              <div class="list-group" id="calendarList" role="tablist">
                <%= link_to 'View Calendar', calendar_path, :class => 'list-group-item list-group-item-action dash-action' %>
                <%= link_to 'View/Edit Week', calendar_week_index_path, :class => 'list-group-item list-group-item-action dash-action' %>
              </div>
            </div>
          </div>
        </div>

        <div class="card">
          <div class="card-header" role="tab" id="headingFour">
            <a class="list-group-item list-group-item-action dash-menu" role="tab" data-toggle="collapse" href="#collapseFour" aria-expanded="true" aria-controls="collapseFour">MowFlow Schedule</a>
          </div>
          <div id="collapseFour" class="collapse" role="tabpanel" aria-labelledby="headingFour" data-parent="#accordion">
            <div class="card-body">
              <div class="list-group" id="mowFlowList" role="tablist">
                <%= link_to 'Optimize Calendar', mow_flow_path, :class => 'list-group-item list-group-item-action dash-action' %>
                <%= link_to "Assign Work", non_optimized_path, :class => 'list-group-item list-group-item-action dash-action' %>
                <%= link_to "Work Schedule", in_progress_path, :class => 'list-group-item list-group-item-action dash-action' %>
              </div>
            </div>
          </div>
        </div>

        <div class="card">
          <div class="card-header" role="tab" id="headingFive">
            <a class="list-group-item list-group-item-action dash-menu" role="tab" data-toggle="collapse" href="#collapseFive" aria-expanded="true" aria-controls="collapseFive">Business</a>
          </div>
          <div id="collapseFive" class="collapse" role="tabpanel" aria-labelledby="headingFive" data-parent="#accordion">
            <div class="card-body">
              <div class="list-group" id="businessList" role="tablist">
                <%= link_to 'Edit Business', my_business_path, :class => 'list-group-item list-group-item-action dash-action' %>
              </div>
            </div>
          </div>
        </div>

         <div class="card">
          <div class="card-header" role="tab" id="headingSix">
            <a class="list-group-item list-group-item-action dash-menu" role="tab" data-toggle="collapse" href="#collapseSix" aria-expanded="true" aria-controls="collapseSix">Schedule History</a>
          </div>
          <div id="collapseSix" class="collapse" role="tabpanel" aria-labelledby="headingSix" data-parent="#accordion">
            <div class="card-body">
              <div class="list-group" id="schedHistoryList" role="tablist">
                <a class="list-group-item list-group-item-action dash-action" data-toggle="list" href="#profile" role="tab">View Last</a>
                <a class="list-group-item list-group-item-action dash-action" data-toggle="list" href="#profile" role="tab">View All</a>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/partials/_navbar.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to 'MowFlow', root_path, :class => 'navbar-brand navButtonWidth nav-menu-custom' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <% if current_user %>
          <ul class="navbar-nav">
            <li class="nav-item navButtonWidth my-auto">
              <%= link_to "Dashboard", dashboard_path, :class => 'nav-link nav-menu-custom' %>
            </li>
            <li class="nav-item navButtonWidth my-auto">
              <%= link_to "Edit Profile", edit_user_path(current_user.id), :class => 'nav-link nav-menu-custom' %>
            </li>
            </ul>
            <ul class="navbar-nav ml-auto">
            <li class="nav-item navButtonWidth my-auto">
              <p class="nav-link my-auto"> Logged in as <%= current_user.first_name %> </p>
            </li>
            <li class="nav-item navButtonWidth my-auto">
              <%= link_to "Logout", :logout, method: :post, :class => 'nav-link nav-menu-custom' %>
            </li>
            </ul>
        <% else %>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item navButtonWidth my-auto">
              <%= link_to "Register", new_user_path , :class => 'nav-link nav-menu-custom' %>
            </li>
            <li class="nav-item navButtonWidth my-auto">
              <%= link_to "Login", :login, :class => 'nav-link nav-menu-custom' %>
            </li>
          </ul>
        <% end %>
    </div>
  </nav>
    