config/routes.rb
Rails.application.routes.draw do
  get 'calendar_week/show'

  get 'calendar/show'

  root :to => 'pages#home'
  resources :user_sessions
  resources :users
  resources :businesses, shallow: true do
    resources :user_businesses
  end
  resources :clients
  resources :scheduled_locations
  resource :calendar, only: [:show], controller: :calendar
  resource :mow_flow, only: [:show], controller: :mow_flow
  resources :calendar_week do
    collection do
      patch :sort
    end
  end

  get 'home', to: 'pages#home', as: 'home'
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'my_business', to: 'businesses#show', as: 'my_business'
  get 'client_jobs/:id', to: 'scheduled_locations#client_jobs', as: 'client_jobs'
  get 'reschedule_job/:id', to: 'scheduled_locations#reschedule_job', as: 'reschedule_job'
  patch 'reschedule_job/:id', to: 'scheduled_locations#reschedule_job_update', as: 'reschedule_job_update'
  get 'non_optimized', to: 'mow_flow#show_one_day', as: 'non_optimized'
  post 'mow_flow_opto', to: 'mow_flow#optimize_list', as: 'mow_flow_opto'
  get 'mow_flow_save', to: 'mow_flow#save_list', as: 'mow_flow_save'
  get 'in_progress', to: 'mow_flow#in_progress', as: 'in_progress'
  get 'print_list', to: 'mow_flow#print_list', as: 'print_list'
  post 'save_progress', to: 'mow_flow#save_progress', as: 'save_progress'
  get 'reschedule_in_progress', to: 'mow_flow#reschedule_in_progress', as: 'reschedule_in_progress'
  post 'save_reschedule_in_progress', to: 'mow_flow#save_reschedule_in_progress', as: 'save_reschedule_in_progress'
  get 'skipped_jobs', to: 'mow_flow#skipped_jobs', as: 'skipped_jobs'
  post 'save_skipped_jobs', to: 'mow_flow#save_skipped_jobs', as: 'save_skipped_jobs'
  get 'reschedule_skipped_jobs', to: 'mow_flow#reschedule_skipped_jobs', as: 'reschedule_skipped_jobs'
  post 'save_reschedule_skipped_jobs', to: 'mow_flow#save_reschedule_skipped_jobs', as: 'save_reschedule_skipped_jobs'
  get 'cancel_skipped_jobs', to: 'mow_flow#cancel_skipped_jobs', as: 'cancel_skipped_jobs'
  post 'save_cancel_skipped_jobs', to: 'mow_flow#save_cancel_skipped_jobs', as: 'save_cancel_skipped_jobs'
  get 'new_depot', to: 'scheduled_locations#new_depot', as: 'new_depot'
  post 'create_depot', to: 'scheduled_locations#create_depot', as: 'create_depot'
  get 'edit_depot', to: 'scheduled_locations#edit_depot', as: 'edit_depot'
  patch 'update_depot', to: 'scheduled_locations#update_depot', as: 'update_depot'
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  
    validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
    validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
    validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  
    validates :email, uniqueness: true
    has_many :user_businesses
    has_one :business, through: :user_businesses
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:index, :new, :create]
  # before_action :set_user, only: [:show, :edit, :update, :destroy] # <- Delete

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    set_user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    set_user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        # redirect_to(:users, notice: 'User was successfully created')
        format.html { redirect_to login_path, notice: 'User was successfully created.' }
        # format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, id: :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, id: :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, id: :email %>
  </div>
  <div class="field">
   <%= f.label :password %><br />
   <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <%= render :partial => 'partials/dashboard' %>

  <div class="col-xs-8 offset-md-1">
    <h1>Editing User</h1>

    <%= render 'form', user: @user %>

    <%= link_to 'Show', @user, :class => 'btn btn-primary' %>
    <%= link_to 'Back', home_path, :class => 'btn btn-primary' %>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <%= render :partial => 'partials/dashboard' %>

  <div class="col-xs-8 offset-md-1">
    <h1>Users</h1>

    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>Email</th>
          <th>Show</th>
          <th>Edit</th>
          <th>Delete</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.email %></td>
            <td><%= link_to 'Show', user, :class => 'btn btn-primary btn-sm' %></td>
            <td><%= link_to 'Edit', edit_user_path(user), :class => 'btn btn-primary btn-sm' %></td>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-primary btn-sm' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New User', new_user_path, :class => 'btn btn-primary' %>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  

  <div class="col-xs-8 offset-md-1">
    <h1>New User</h1>

    <%= render 'form', user: @user %>

    <%= link_to 'Back', users_path, :class => 'btn btn-primary' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <%= render :partial => 'partials/dashboard' %>

  <div class="col-xs-8 offset-md-1">
    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>


    <%= link_to 'Edit', edit_user_path(@user), :class => 'btn btn-primary' %>
    <%= link_to 'Back', users_path, :class => 'btn btn-primary' %>
  </div>
</div>