config/routes.rb
Rails.application.routes.draw do
  get 'calendar_week/show'

  get 'calendar/show'

  root :to => 'pages#home'
  resources :user_sessions
  resources :users
  resources :businesses, shallow: true do
    resources :user_businesses
  end
  resources :clients
  resources :scheduled_locations
  resource :calendar, only: [:show], controller: :calendar
  resource :mow_flow, only: [:show], controller: :mow_flow
  resources :calendar_week do
    collection do
      patch :sort
    end
  end

  get 'home', to: 'pages#home', as: 'home'
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'my_business', to: 'businesses#show', as: 'my_business'
  get 'client_jobs/:id', to: 'scheduled_locations#client_jobs', as: 'client_jobs'
  get 'reschedule_job/:id', to: 'scheduled_locations#reschedule_job', as: 'reschedule_job'
  patch 'reschedule_job/:id', to: 'scheduled_locations#reschedule_job_update', as: 'reschedule_job_update'
  get 'non_optimized', to: 'mow_flow#show_one_day', as: 'non_optimized'
  post 'mow_flow_opto', to: 'mow_flow#optimize_list', as: 'mow_flow_opto'
  get 'mow_flow_save', to: 'mow_flow#save_list', as: 'mow_flow_save'
  get 'in_progress', to: 'mow_flow#in_progress', as: 'in_progress'
  get 'print_list', to: 'mow_flow#print_list', as: 'print_list'
  post 'save_progress', to: 'mow_flow#save_progress', as: 'save_progress'
  get 'reschedule_in_progress', to: 'mow_flow#reschedule_in_progress', as: 'reschedule_in_progress'
  post 'save_reschedule_in_progress', to: 'mow_flow#save_reschedule_in_progress', as: 'save_reschedule_in_progress'
  get 'skipped_jobs', to: 'mow_flow#skipped_jobs', as: 'skipped_jobs'
  post 'save_skipped_jobs', to: 'mow_flow#save_skipped_jobs', as: 'save_skipped_jobs'
  get 'reschedule_skipped_jobs', to: 'mow_flow#reschedule_skipped_jobs', as: 'reschedule_skipped_jobs'
  post 'save_reschedule_skipped_jobs', to: 'mow_flow#save_reschedule_skipped_jobs', as: 'save_reschedule_skipped_jobs'
  get 'cancel_skipped_jobs', to: 'mow_flow#cancel_skipped_jobs', as: 'cancel_skipped_jobs'
  post 'save_cancel_skipped_jobs', to: 'mow_flow#save_cancel_skipped_jobs', as: 'save_cancel_skipped_jobs'
  get 'new_depot', to: 'scheduled_locations#new_depot', as: 'new_depot'
  post 'create_depot', to: 'scheduled_locations#create_depot', as: 'create_depot'
  get 'edit_depot', to: 'scheduled_locations#edit_depot', as: 'edit_depot'
  patch 'update_depot', to: 'scheduled_locations#update_depot', as: 'update_depot'
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/mow_flow_controller.rb
class MowFlowController < ApplicationController
  @@save_hash = {}
  @@jobs_hash = {}
  @@skipped_jobs_hash = {}
  @@cancel_skipped_jobs_hash = {}
  
  require 'uri'

  #non-optimization scheduling
  def show_one_day
    @date = Date.today
    # @jobs = ScheduledLocation.all.group_by(&:next_mow_date)
    @jobs = ScheduledLocation.where('next_mow_date = ? AND in_progress IS ?', @date, nil)
                                    .group_by(&:next_mow_date)

    @save_jobs = ScheduledLocation.where('next_mow_date = ? AND in_progress IS ?', @date, nil).as_json
    @opto_location_hashes = {}
    @opto_location_hashes["#{@date}"] = @save_jobs
    # Sets class varible @@save_hash - to be accessed from next method: save_list
    opto_hash_list(@opto_location_hashes)
  end

  #optimization scheduling
  def show
    # @jobs = ScheduledLocation.all.group_by(&:next_mow_date)
    @dates = Date.today..(Date.today + 2)
    @search_dates = @dates.to_a
    @jobs = {}
    @search_dates.each do |date|
      @jobs_per_date = ScheduledLocation.where("next_mow_date = ? AND in_progress IS ?", date, nil).as_json
      if @jobs_per_date.length > 0
        @jobs_arr = []
        @jobs_per_date.each do |job_date|
          @jobs_arr.push(job_date)
        end
        @jobs[date.strftime("%F")] = @jobs_arr
      end
    end
    @optimize_days = [1,2,3]
  end
  
  def optimize_list
    # get depot
    @business = get_business
    @depot = ScheduledLocation.where('business_id = ? AND depot IS ?', @business.id, true).first.as_json
    # get number of routes (days) for optimization
    @number_of_routes = params["days"].to_i
    # get range of dates to for query
    @number_of_days = params["days"].to_i - 1
    @dates = Date.today..(Date.today + @number_of_days)
    @dates = @dates.to_a
    # get jobs from database that are equal to the date range and are not in_progress
        # @jobs = ScheduledLocation.where(:next_mow_date => @dates).as_json  # OLD CODE
    @jobs = []
    @dates.each do |date|
      @job_date = ScheduledLocation.where("next_mow_date = ? AND in_progress IS ?", date, nil).as_json
      @jobs.push(@job_date)
    end
    @jobs = @jobs.flatten()

    # add the depot to the beginning of the array
    @jobs.unshift(@depot)
    # arrange job IDs in array
    @location_ids = []
    # arrange job durations in array
    @duration_per_location = []
    # put jobs into coordinate array following this format:
    # "lng1,lat1;lng2,lat2;"
    @coordinates_string = ""
    @jobs.each do |job|
      @location_ids.push(job["id"])
      @duration_per_location.push(job["duration_id"].to_i)
      @coordinates_string += job["coordinates"] + ";"
    end
    @coordinates_string = @coordinates_string.chop!

    # Generate Location Matrix from coordinates
    @location_matrix_response = create_matrix(@coordinates_string)

    # If Matrix OSRM API works then run Google OR-Tools
    if @location_matrix_response[0] == "ok"
      @error_true = false
      @location_matrix = @location_matrix_response[1]
      @data_hash_for_optimization = {
                                      location_ids: @location_ids,
                                      location_matrix: @location_matrix,
                                      duration_per_location: @duration_per_location,
                                      number_of_routes: @number_of_routes 
                                    }
      # Run Google OR-TOOLS Python Script to Optimize for best driving route
      @opto_data_response = optimize_mine(@data_hash_for_optimization)
      # If Google OR-Tools works
      if @opto_data_response[0] == "ok"
        @opto_data = @opto_data_response[1]
        # loop through data and push location id arrays (without the depots) to containing hash
        # {"date"=>[loc_hash,loc_hash], "date-2"=>[loc_hash,loc_hash,loc_hash] }
        @opto_location_hashes = {}
        limit = @number_of_routes
        @dates_array = @dates.to_a
        for i in 1..limit
          @location_array = []
          @lookup_ids = @opto_data["route_day_#{i}"]["location_ids"].slice(1,(@opto_data["route_day_#{i}"]["location_ids"].length - 2))
          @lookup_ids.each do |id|
            @location_array.push( ScheduledLocation.where("id = ?", id).first.as_json )
          end
          @opto_location_hashes["#{@dates_array[i-1]}"] = @location_array
        end
        # Sets class varible @@save_hash - to be accessed from next method: save_list
        opto_hash_list(@opto_location_hashes)
      else
        @error_true = true
        @error_msg = @opto_data_response[1]    
      end
    else
      @error_true = true
      @error_msg = @location_matrix_response[1]
    end

    render 'results'
  end

  def save_list
    # Get class variable
    @hash_from_save = opto_hash_list
    #  LOOP: Set service date of each location hash to key of the hash: @hash_from_save[date] = [{location},{location}, etc]
    @hash_from_save.each do |job_list|
      @opto_date = job_list[0]
      # set position
      position = 1
      job_list[1].each do |job|
        # set service date to @opto_date
        @opto_job = ScheduledLocation.where("id = ?", job["id"]).first
        @opto_job.service_date = @opto_date
        # if service_date is today then switch in_progress boolean to true
        if @opto_date == Date.today.strftime("%F")
          @opto_job.in_progress = true
        end
        # save position - order of jobs
        @opto_job.position = position
        @opto_job.update(scheduled_location_params)
        position += 1
      end
    end
    redirect_to in_progress_path
  end
  
  def in_progress
    @business = get_business
    @date = Date.today.strftime("%F")
    # get in_progress jobs from previous days
    @previous_jobs = ScheduledLocation.where(
                                            "business_id = ? AND service_date < ? AND in_progress IS ?", 
                                            @business.id, @date, true)
    # previous job status options
    @prev_in_prog_options = ["Not Done","Done","Reschedule for Set Date"]
    # get jobs where business_id, in_progress = true, service_date = today
    @jobs = ScheduledLocation.where(
                                    "business_id = ? AND service_date = ? AND in_progress IS ?", 
                                    @business.id, @date, true)
    # current in_progress job status options
    @in_prog_options = ["Not Done","Done","Reschedule for Tomorrow","Reschedule for Set Date"]
    # get jobs where business_id, in_progress = true, service_date = today
    @future_jobs = ScheduledLocation.where(
                                    "business_id = ? AND service_date > ? AND in_progress IS ?", 
                                    @business.id, @date, true)
    # current in_progress job status options
    @future_in_prog_options = ["Not Done","Reschedule for Set Date"]
    
    # Sets class varible @@jobs_hash - to be accessed from next method: save_progress
    @all_jobs = @jobs + @previous_jobs + @future_jobs
    in_progress_jobs_hash(@all_jobs)
    @maps_params = build_map_params(@jobs)
    render 'in_progress'
  end

  def print_list
    @business = get_business
    @day = Date.today.strftime("%A")
    @date = Date.today.strftime("%F")
    @jobs = ScheduledLocation.where(
                                    "business_id = ? AND service_date = ? AND in_progress IS ?", 
                                    @business.id, @date, true)
    respond_to do |format|
      format.html
      format.pdf do
        pdf = ReportPdf.new(@jobs,@business.name)
        send_data pdf.render, filename: "#{@date}_#{@day}_schedule.pdf", type: 'application/pdf', disposition: "inline"
      end
    end
  end

  def save_progress
    @jobs = in_progress_jobs_hash
    @reschedule_jobs = []
    @reschedule_redirect = false
    # loop through progress update select and handle params accordingly
    # params options: "Not Done", "Done", "Reschedule for Tomorrow", "Reschedule for Later Date"
    @jobs.each do |job|
      @progress = params["#{job["id"]}"]
      # If "Not Done", then do nothing
      # If "Done", then switch in_progress to false, set date_mowed to today, set next_mow_date, set service_date to nil, and position to nil
      if @progress == "Done"
        scheduled_location_params_done = scheduled_location_params
        @scheduled_location = ScheduledLocation.where("id = ?", job["id"]).first
        scheduled_location_params_done[:in_progress] = nil
        scheduled_location_params_done[:date_mowed] = Date.today
        scheduled_location_params_done[:next_mow_date] = get_next_mow_date(Date.today, job["mow_frequency"])
        scheduled_location_params_done[:service_date] = nil
        scheduled_location_params_done[:position] = nil
        @scheduled_location.update(scheduled_location_params_done)
      end
      
      # Reschedule Jobs for tomorrow 
      if @progress == "Reschedule for Tomorrow"
        scheduled_location_params_done = scheduled_location_params
        @scheduled_location = ScheduledLocation.where("id = ?", job["id"]).first
        scheduled_location_params_done[:service_date] = (Date.today + 1)
        scheduled_location_params_done[:next_mow_date] = (Date.today + 1)
        scheduled_location_params_done[:position] = nil
        @scheduled_location.update(scheduled_location_params_done)
      end

      # Reschedule Jobs for later date
      if @progress == "Reschedule for Set Date"
        @scheduled_location = ScheduledLocation.where("id = ?", job["id"]).first
        @reschedule_jobs.push(@scheduled_location)
        # Set the the redirect to rescheduling the remaning jobs marked "Reschedule for Later Date"
        @reschedule_redirect = true
      end
    end

    if @reschedule_redirect
      in_progress_jobs_hash(@reschedule_jobs)
      redirect_to reschedule_in_progress_path and return
    end
    respond_to do |format|
      format.html { redirect_to in_progress_path, notice: 'Job(s) status was successfully updated.' }
    end

app/helpers/mow_flow_helper.rb
module MowFlowHelper
end

app/views/mow_flow/cancel_skipped_jobs.html.erb
<div class="row">
  <%= render :partial => 'partials/dashboard' %>

  <div class="col-sm-8 offset-md-1">
    <% if @jobs.length > 0 %>
      <h1>Cancel Skipped Jobs</h1>
      <h5>These jobs and locations will be deleted.</h5>
      <h5>The client information will remain saved in the system</h5>
      <div class="row">
        <div class="col-sm-8">
          <%= form_for :cancel_skipped_jobs, url: save_cancel_skipped_jobs_path do |f| %>
            <div class="list-group col-sm-10">
              <% @jobs.each do |job| %>
                <div class="list-group-item">
                  <%= job.location_desc %> |
                  <%= "#{job.street_address}, #{job.city}, #{job.state}" %>
                  <div class="field">
                      <%= f.label 'Delete from Database?' %>
                      <%= select_tag "#{job.id}", options_for_select(@cancel_skipped_job_options) %>
                    </div>
                  </div>            
                </div>
              <% end %>
              <div class="actions">
                <%= f.submit "Confirm", :class => 'btn btn-danger' %>
              </div>
            </div>

          <% end %>
        </div>
      </div>
      <% else %>
      <h3>There are no jobs to be cancelled and deleted</h3>
      <%= link_to 'Back', dashboard_path, :class => 'btn btn-primary' %>
    <% end %>
    
  </div>
</div>

app/views/mow_flow/in_progress.html.erb
<div class="row">
  <%= render :partial => 'partials/dashboard' %>

  <div class="col-sm-8 offset-md-1">
    <% if @previous_jobs.length > 0 %>
      <h1>Previous Work</h1>
      <h5>Please update status immediately:</h5>
      <div class="row">
        <div class="col-sm-8">
          <%= form_for :in_progress, url: save_progress_path do |f| %>
            
            <% @previous_jobs.each do |job| %>
            
              <%= job.location_desc %> |
              <%= "#{job.street_address}, #{job.city}, #{job.state}" %>
              <div class="field">
                <%= f.label 'Work Status' %>
                <%= select_tag "#{job.id}", options_for_select(@prev_in_prog_options) %>
              </div>
              
            <% end %>

            <div class="actions">
              <%= f.submit "Update", :class => 'btn btn-primary' %>
            </div>

          <% end %>
        </div>
      </div>
      <div class="col-sm-12">
        <div style='border-bottom:4px solid #2f4f4f; margin-top:10px; margin-bottom:10px;'></div>
      </div>
    <% end %>

    <% if @jobs.length > 0 %>
      <h1>Work In Progress</h1>
      <div class="row">
        <div class="col-sm-8">
          <%= form_for :in_progress, url: save_progress_path do |f| %>
            
            <% @jobs.each do |job| %>
            
              <%= job.location_desc %> |
              <%= "#{job.street_address}, #{job.city}, #{job.state}" %>
              <div class="field">
                <%= f.label 'Work Status' %>
                <%= select_tag "#{job.id}", options_for_select(@in_prog_options) %>
              </div>
              
            <% end %>

            <div class="actions">
              <%= f.submit "Update", :class => 'btn btn-primary' %>
            </div>

          <% end %>
        </div>
        <div class="col-sm-4">
          <%= link_to 'Print List', print_list_path(format: "pdf"), :class => 'btn btn-primary' %>
          <a href="<%= @maps_params %>" class="btn btn-primary" target="_blank">Open in Google Maps</a>
        </div>
      </div>
      <div class="col-sm-12">
        <div style='border-bottom:4px solid #2f4f4f; margin-top:10px; margin-bottom:10px;'></div>
      </div>
    <% end %>

    <% if @future_jobs.length > 0 %>
      <h3>Future Confirmed Work</h3>
      <div class="row">
        <div class="col-sm-8">
          <%= form_for :in_progress, url: save_progress_path do |f| %>
            
            <% @future_jobs.each do |job| %>
            
              <%= job.location_desc %> |
              <%= "#{job.street_address}, #{job.city}, #{job.state}" %>
              <div class="field">
                <%= f.label 'Work Status' %>
                <%= select_tag "#{job.id}", options_for_select(@in_prog_options) %>
              </div>
              
            <% end %>

            <div class="actions">
              <%= f.submit "Update", :class => 'btn btn-primary' %>
            </div>

          <% end %>
        </div>
      </div>
      <div class="col-sm-12">
        <div style='border-bottom:4px solid #2f4f4f; margin-top:10px; margin-bottom:10px;'></div>
      </div>
    <% end %>

  </div>
</div>

app/views/mow_flow/print_list.html.erb
<h1>Today's Schedule - <%= @date %></h1>
<div class="row">
  <div class="col-sm-8">
      <% @jobs.each do |job| %>
      <p>
        <%= job.location_desc %> |
        <%= "#{job.street_address}, #{job.city}, #{job.state}" %>
      </p>
      <% end %>
  </div>
</div>

app/views/mow_flow/reschedule_in_progress.html.erb
<div class="row">
  <%= render :partial => 'partials/dashboard' %>

  <div class="col-sm-8 offset-md-1">
    <h1>Work In Progress</h1>
    <div class="row">
      <div class="col-sm-8">
        <%= form_for :reschedule_in_progress, url: save_reschedule_in_progress_path do |f| %>
          
          <% @jobs.each do |job| %>
          
            <%= job.location_desc %> |
            <%= "#{job.street_address}, #{job.city}, #{job.state}" %>
            <div class="field">
              <%= f.label 'Reschedule Job for' %>
              <%=  date_select("#{job.id}", "date", order: [:day, :month, :year]) %>
            </div>
            
          <% end %>

          <div class="actions">
            <%= f.submit "Update", :class => 'btn btn-primary' %>
          </div>

        <% end %>
      </div>
      <div class="col-sm-4">
        <%= link_to 'Back', in_progress_path, :class => 'btn btn-primary' %>
      </div>
    </div>
    
  </div>
</div>

app/views/mow_flow/reschedule_skipped_jobs.html.erb
<div class="row">
  <%= render :partial => 'partials/dashboard' %>

  <div class="col-sm-8 offset-md-1">
    <h1>Reschedule Skipped Jobs</h1>
    <div class="row">
      <div class="col-sm-8">
        <%= form_for :reschedule_skipped_jobs, url: save_reschedule_skipped_jobs_path do |f| %>
          
          <% @jobs.each do |job| %>
          
            <%= job.location_desc %> |
            <%= "#{job.street_address}, #{job.city}, #{job.state}" %>
            <div class="field">
              <%= f.label 'Reschedule Job for' %>
              <%=  date_select("#{job.id}", "date", order: [:day, :month, :year]) %>
            </div>
            
          <% end %>

          <div class="actions">
            <%= f.submit "Update", :class => 'btn btn-primary' %>
          </div>

        <% end %>
      </div>
      <div class="col-sm-4">
        <%= link_to 'Back', skipped_jobs_path, :class => 'btn btn-primary' %>
      </div>
    </div>
    
  </div>
</div>

app/views/mow_flow/results.html.erb
<div class="row">
  <%= render :partial => 'partials/dashboard' %>

  <div class="col-sm-8 offset-md-1">

    <h1>Optimized List</h1>
    <% if @error_true %>
      <p>There was a problem optimizing this list. Error: <%=  @error_msg %>
      <div id="jobs" class="row"> 
        <div id="date-col" class="list-group col-sm-8">
        <p>Click "Back" and try again.  If problem persists, you will have to schedule the jobs by clicking "Select Today's Schedule" under the MowFlow tab on the left</p>
        </div>
        <div class="col-sm-3">
          <%= link_to 'Back', dashboard_path %>
        </div>
      </div>
    <% else %>
      <div id="jobs" class="row"> 
        <% @dates.each do |date|%>
          <div id="date-col" class="list-group col-sm-3" data-date="<%= date %>">
            <div class="text-center">
              <%= "#{date.strftime("%b")} #{date.day}"%>
            </div>
            <%if @opto_location_hashes["#{date}"]%>
              <% @opto_location_hashes["#{date}"].each do |job|%>
                <li class="list-group-item"><%= job["location_desc"] %></li>
              <%end%>
            <% end %>
          </div>
        <% end %>
        <div class="col-sm-3">
          <%= link_to 'Confirm List', mow_flow_save_path, :class => 'btn btn-primary' %>
          <%= link_to 'Back', dashboard_path, :class => 'btn btn-primary' %>
        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/mow_flow/save_list.html.erb
<div class="row">
  <%= render :partial => 'partials/dashboard' %>

  <div class="col-sm-8 offset-md-1">

    <h1>Optimized List</h1>
      <% if @error_true %>
        <p>There was a problem optimizing this list. Error: <%=  @error_msg %>
        <div id="jobs" class="row"> 
          <div id="date-col" class="list-group col-sm-3">
          </div>
          <div class="col-sm-3">
            <%= link_to 'Back', dashboard_path %>
          </div>
        </div>
      <% else %>
        <div id="jobs" class="row"> 
          <% @dates.each do |date|%>
            <div id="date-col" class="list-group col-sm-3" data-date="<%= date %>">
              <div class="text-center">
                <%= "#{date.strftime("%b")} #{date.day}"%>
              </div>
              <%if @opto_location_hashes["#{date}"]%>
                <% @opto_location_hashes["#{date}"].each do |job|%>
                  <li class="list-group-item"><%= job["location_desc"] %></li>
                <%end%>
              <% end %>
            </div>
          <% end %>
          <div class="col-sm-3">
            <%= link_to 'Back', dashboard_path, :class => 'btn btn-primary' %>
            <%= link_to 'Print List', mow_flow_save_path, :class => 'btn btn-primary' %>
          </div>
        </div>
      <% end %>

  </div>
</div>

app/views/mow_flow/show.html.erb
<div class="row">
  <%= render :partial => 'partials/dashboard' %>

  <div class="col-sm-8 offset-md-1">

    <h1>Choose Days to Optimize</h1>
      <div id="jobs" class="row"> 
        <% @dates.each do |date|%>
          <div id="date-col" class="list-group col-sm-3" data-date="<%= date %>">
            <div class="text-center">
              <%= "#{date.strftime("%b")} #{date.day}"%>
            </div>
          <%if @jobs["#{date}"]%>
            <% @jobs["#{date}"].each do |job|%>
              <%= link_to "#{job["location_desc"]}", scheduled_location_path(job["id"]), class: "list-group-item dark-a", next_mow_date: date %>
            <%end%>
          <% end %>
          </div>
        <% end %>
        <div class="col-sm-3">
          <%= form_for :optimize_days, url: mow_flow_opto_path do |f| %>
            <div class="field">
              <%= f.label 'Optimization Range (days)' %>
              <%= select_tag :days, options_for_select(@optimize_days) %>
            </div>
        
            <div class="actions">
              <%= f.submit 'Optimize Schedule', :class => 'btn btn-primary' %>
            </div>
          <% end %>
          <%= link_to 'Back', dashboard_path, :class => 'btn btn-primary' %>
        </div>
      </div>


  </div>
</div>

app/views/mow_flow/show_one_day.html.erb
<div class="row">
  <%= render :partial => 'partials/dashboard' %>

  <div class="col-sm-8 offset-md-1">

    <h1>Confirm Daily Schedule</h1>
      <p>This schedule will not be optimized</p>
      <div id="jobs" class="row"> 
        <div id="date-col" class="list-group col-sm-6 text-center" data-date="<%= @date %>">
          <div class="text-center">
            <%= "#{@date.strftime("%b")} #{@date.day}"%>
          </div>
          <%if @jobs[@date]%>
            <% @jobs[@date].each do |job|%>
              <%= link_to job.location_desc, job, class: "list-group-item dark-a", id: dom_id(job), next_mow_date: @date %>
            <%end%>
          <% else %>
            <p>There are no jobs scheduled for today.</p>
          <% end %>
        </div>
        <div class="col-sm-3">
          <%= link_to 'Confirm List', mow_flow_save_path, :class => 'btn btn-primary' %>
          <%= link_to 'Back', dashboard_path, :class => 'btn btn-primary' %>
        </div>
      </div>

  </div>
</div>

app/views/mow_flow/skipped_jobs.html.erb
<div class="row">
  <%= render :partial => 'partials/dashboard' %>

  <div class="col-sm-8 offset-md-1">

    <% if @previous_skipped_jobs.length > 0 %>
      <%= form_for :skipped_jobs, url: save_skipped_jobs_path do |f| %>
            
        <h2 class="offset-md-1">Previous Work Unconfirmed</h2>
        <h5 class="offset-md-1">Please schedule or cancel these jobs:</h5>
        <div class="row">
          <div class="list-group col-sm-10 offset-md-1">
            <% @previous_skipped_jobs.each do |job| %>
              <div class="list-group-item" >
                <%= "#{job.location_desc} | #{job.street_address}, #{job.city}, #{job.state} | Scheduled for: #{job.next_mow_date}" %>
                <div class="field">
                  <%= f.label 'Work Status' %>
                  <%= select_tag "#{job.id}", options_for_select(@skipped_job_options) %>
                </div>
              </div>
            <% end %>
            <div class="actions">
              <%= f.submit "Update", :class => 'btn btn-primary' %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <h2 class="offset-md-1">No Previous Work Unconfirmed</h2>
      <h5 class="offset-md-1">Good Job</h5>
    <% end %>
    <div class="row">
    <%= link_to 'Back', dashboard_path, :class => 'btn btn-primary mx-auto' %>
    </div>
  </div>
</div>